package com.gamemaker.ExtensionCore.ExtBridge;
import java.lang.String;
import java.nio.ByteBuffer;
import ${YYAndroidPackageName}.GMExtUtils;

public final class GMPhotonBridge {
    static {
        // this is the extension lib name
        System.loadLibrary("GMPhoton");
        nativeRegister();
    }
    // this registers the native functions on the C++ layer
    private static native void nativeRegister();

    public static String __EXT_JAVA__GetExtensionOption(String extName, String optName)
    {
        return GMExtUtils.GetExtensionOption(extName, optName);
    }

    public static native double __EXT_JNI__GMPhoton_invocation_handler(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__GMPhoton_queue_buffer(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_init();
    public static native double __EXT_JNI__photon_realtime_shutdown();
    public static native double __EXT_JNI__photon_realtime_service();
    public static native double __EXT_JNI__photon_realtime_connect(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_disconnect();
    public static native double __EXT_JNI__photon_realtime_select_region(String region);
    public static native double __EXT_JNI__photon_realtime_reconnect_and_rejoin();
    public static native double __EXT_JNI__photon_realtime_fetch_server_timestamp();
    public static native double __EXT_JNI__photon_realtime_operation_join_lobby(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_leave_lobby(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_create_room(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_join_or_create_room(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_join_room(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_join_random_room(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_leave_room(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_join_random_or_create_room(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_get_room_list(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_lobby_stats(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_find_friends(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_web_rpc(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_change_groups(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_custom_auth_next_step(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_raise_event_string(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_operation_raise_event_buffer(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_get_buffer_event_queue_count();
    public static native double __EXT_JNI__photon_realtime_clear_buffer_event_queue();
    public static native double __EXT_JNI__photon_realtime_peek_next_buffer_event_size();
    public static native double __EXT_JNI__photon_realtime_peek_next_buffer_event_code();
    public static native double __EXT_JNI__photon_realtime_receive_one_event_buffer(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_realtime_is_initialized();
    public static native double __EXT_JNI__photon_realtime_is_connected();
    public static native double __EXT_JNI__photon_realtime_is_in_game_room();
    public static native double __EXT_JNI__photon_realtime_is_in_room();
    public static native double __EXT_JNI__photon_realtime_is_in_lobby();
    public static native String __EXT_JNI__photon_realtime_get_current_room_name();
    public static native double __EXT_JNI__photon_realtime_get_local_player_number();
    public static native double __EXT_JNI__photon_realtime_get_server_time_offset();
    public static native double __EXT_JNI__photon_realtime_get_server_time();
    public static native double __EXT_JNI__photon_realtime_get_bytes_in();
    public static native double __EXT_JNI__photon_realtime_get_bytes_out();
    public static native double __EXT_JNI__photon_realtime_get_state(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_realtime_get_round_trip_time();
    public static native double __EXT_JNI__photon_realtime_get_round_trip_time_variance();
    public static native double __EXT_JNI__photon_realtime_get_disconnected_cause(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native String __EXT_JNI__photon_realtime_get_user_id();
    public static native double __EXT_JNI__photon_realtime_get_count_players_ingame();
    public static native double __EXT_JNI__photon_realtime_get_count_games_running();
    public static native double __EXT_JNI__photon_realtime_get_count_players_online();
    public static native String __EXT_JNI__photon_realtime_get_master_server_address();
    public static native String __EXT_JNI__photon_realtime_get_region();
    public static native String __EXT_JNI__photon_realtime_get_region_with_best_ping();
    public static native double __EXT_JNI__photon_realtime_get_friend_list_age();
    public static native double __EXT_JNI__photon_realtime_get_disconnect_timeout();
    public static native double __EXT_JNI__photon_realtime_set_disconnect_timeout(double milliseconds);
    public static native double __EXT_JNI__photon_realtime_get_ping_interval();
    public static native double __EXT_JNI__photon_realtime_set_ping_interval(double milliseconds);
    public static native double __EXT_JNI__photon_realtime_get_auto_join_lobby();
    public static native double __EXT_JNI__photon_realtime_set_auto_join_lobby(double enabled);
    public static native double __EXT_JNI__photon_realtime_get_room_player_count();
    public static native double __EXT_JNI__photon_realtime_get_room_max_players();
    public static native double __EXT_JNI__photon_realtime_get_room_is_open();
    public static native double __EXT_JNI__photon_realtime_get_room_is_visible();
    public static native double __EXT_JNI__photon_realtime_get_master_client_number();
    public static native double __EXT_JNI__photon_realtime_set_master_client(double player_number);
    public static native double __EXT_JNI__photon_realtime_get_room_list_count();
    public static native double __EXT_JNI__photon_realtime_get_room_info_by_index(double index, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_realtime_get_player_count();
    public static native double __EXT_JNI__photon_realtime_get_player_number_by_index(double index);
    public static native String __EXT_JNI__photon_realtime_player_get_name(double player_number);
    public static native String __EXT_JNI__photon_realtime_player_get_user_id(double player_number);
    public static native double __EXT_JNI__photon_realtime_player_is_inactive(double player_number);
    public static native double __EXT_JNI__photon_realtime_player_is_master_client(double player_number);
    public static native double __EXT_JNI__photon_realtime_get_player_numbers(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_debug(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_connected(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_disconnected(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_connection_error(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_client_error(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_server_error(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_warning(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_join_room_event(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_leave_room_event(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_custom_event(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_room_properties_change(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_player_properties_change(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_room_list_update(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_app_stats_update(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_lobby_stats_update(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_cache_slice_changed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_master_client_changed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_properties_change_failed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_custom_authentication_step(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_available_regions(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_secret_receival(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_direct_connection_established(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_direct_connection_failed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_direct_message(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_set_callback_custom_operation_response(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_remove_callback_debug();
    public static native double __EXT_JNI__photon_realtime_remove_callback_connected();
    public static native double __EXT_JNI__photon_realtime_remove_callback_disconnected();
    public static native double __EXT_JNI__photon_realtime_remove_callback_connection_error();
    public static native double __EXT_JNI__photon_realtime_remove_callback_client_error();
    public static native double __EXT_JNI__photon_realtime_remove_callback_server_error();
    public static native double __EXT_JNI__photon_realtime_remove_callback_warning();
    public static native double __EXT_JNI__photon_realtime_remove_callback_join_room_event();
    public static native double __EXT_JNI__photon_realtime_remove_callback_leave_room_event();
    public static native double __EXT_JNI__photon_realtime_remove_callback_custom_event();
    public static native double __EXT_JNI__photon_realtime_remove_callback_room_properties_change();
    public static native double __EXT_JNI__photon_realtime_remove_callback_player_properties_change();
    public static native double __EXT_JNI__photon_realtime_remove_callback_room_list_update();
    public static native double __EXT_JNI__photon_realtime_remove_callback_app_stats_update();
    public static native double __EXT_JNI__photon_realtime_remove_callback_lobby_stats_update();
    public static native double __EXT_JNI__photon_realtime_remove_callback_cache_slice_changed();
    public static native double __EXT_JNI__photon_realtime_remove_callback_master_client_changed();
    public static native double __EXT_JNI__photon_realtime_remove_callback_properties_change_failed();
    public static native double __EXT_JNI__photon_realtime_remove_callback_custom_authentication_step();
    public static native double __EXT_JNI__photon_realtime_remove_callback_available_regions();
    public static native double __EXT_JNI__photon_realtime_remove_callback_secret_receival();
    public static native double __EXT_JNI__photon_realtime_remove_callback_direct_connection_established();
    public static native double __EXT_JNI__photon_realtime_remove_callback_direct_connection_failed();
    public static native double __EXT_JNI__photon_realtime_remove_callback_direct_message();
    public static native double __EXT_JNI__photon_realtime_remove_callback_custom_operation_response();
    public static native double __EXT_JNI__photon_realtime_room_properties_set_string(String key, String value);
    public static native double __EXT_JNI__photon_realtime_room_properties_set_i32(String key, double value);
    public static native double __EXT_JNI__photon_realtime_room_properties_set_f64(String key, double value);
    public static native double __EXT_JNI__photon_realtime_room_properties_set_bool(String key, double value);
    public static native double __EXT_JNI__photon_realtime_room_properties_remove(String key);
    public static native double __EXT_JNI__photon_realtime_room_properties_clear();
    public static native double __EXT_JNI__photon_realtime_room_properties_has(String key);
    public static native String __EXT_JNI__photon_realtime_room_properties_get_string(String key);
    public static native double __EXT_JNI__photon_realtime_room_properties_get_i32(String key);
    public static native double __EXT_JNI__photon_realtime_room_properties_get_f64(String key);
    public static native double __EXT_JNI__photon_realtime_room_properties_get_bool(String key);
    public static native String __EXT_JNI__photon_realtime_room_properties_to_string();
    public static native double __EXT_JNI__photon_realtime_room_properties_get_all(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_realtime_room_properties_cas_string(String key, String expected_value, String new_value);
    public static native double __EXT_JNI__photon_realtime_room_properties_cas_i32(String key, double expected_value, double new_value);
    public static native double __EXT_JNI__photon_realtime_room_properties_cas_f64(String key, double expected_value, double new_value);
    public static native double __EXT_JNI__photon_realtime_room_properties_cas_bool(String key, double expected_value, double new_value);
    public static native double __EXT_JNI__photon_realtime_player_properties_set_local_string(String key, String value);
    public static native double __EXT_JNI__photon_realtime_player_properties_set_local_i32(String key, double value);
    public static native double __EXT_JNI__photon_realtime_player_properties_set_local_f64(String key, double value);
    public static native double __EXT_JNI__photon_realtime_player_properties_set_local_bool(String key, double value);
    public static native double __EXT_JNI__photon_realtime_player_properties_remove_local(String key);
    public static native double __EXT_JNI__photon_realtime_player_properties_clear_local();
    public static native double __EXT_JNI__photon_realtime_player_properties_has_local(String key);
    public static native String __EXT_JNI__photon_realtime_player_properties_get_local_string(String key);
    public static native double __EXT_JNI__photon_realtime_player_properties_get_local_i32(String key);
    public static native double __EXT_JNI__photon_realtime_player_properties_get_local_f64(String key);
    public static native double __EXT_JNI__photon_realtime_player_properties_get_local_bool(String key);
    public static native String __EXT_JNI__photon_realtime_player_properties_to_string_local();
    public static native double __EXT_JNI__photon_realtime_player_properties_get_local_all(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_realtime_player_properties_has_remote(double player_number, String key);
    public static native String __EXT_JNI__photon_realtime_player_properties_get_remote_string(double player_number, String key);
    public static native double __EXT_JNI__photon_realtime_player_properties_get_remote_i32(double player_number, String key);
    public static native double __EXT_JNI__photon_realtime_player_properties_get_remote_f64(double player_number, String key);
    public static native double __EXT_JNI__photon_realtime_player_properties_get_remote_bool(double player_number, String key);
    public static native String __EXT_JNI__photon_realtime_player_properties_to_string_remote(double player_number);
    public static native double __EXT_JNI__photon_realtime_player_properties_get_remote_all(double player_number, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_realtime_peek_next_buffer_event_player_number();
    public static native double __EXT_JNI__photon_chat_init();
    public static native double __EXT_JNI__photon_chat_shutdown();
    public static native double __EXT_JNI__photon_chat_service();
    public static native double __EXT_JNI__photon_chat_select_region(String region);
    public static native double __EXT_JNI__photon_chat_connect(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_disconnect();
    public static native double __EXT_JNI__photon_chat_operation_subscribe(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_operation_unsubscribe(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_operation_publish_message(String channel_name, String message);
    public static native double __EXT_JNI__photon_chat_operation_send_private_message(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_operation_set_online_status(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_operation_add_friends(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_operation_remove_friends(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_is_initialized();
    public static native double __EXT_JNI__photon_chat_is_connected();
    public static native double __EXT_JNI__photon_chat_get_state(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_chat_get_disconnect_cause(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native String __EXT_JNI__photon_chat_get_user_id();
    public static native String __EXT_JNI__photon_chat_get_region();
    public static native double __EXT_JNI__photon_chat_get_server_time();
    public static native double __EXT_JNI__photon_chat_get_server_time_offset();
    public static native double __EXT_JNI__photon_chat_get_bytes_in();
    public static native double __EXT_JNI__photon_chat_get_bytes_out();
    public static native double __EXT_JNI__photon_chat_get_channel_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__photon_chat_get_channel_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_get_channel_message_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__photon_chat_get_channel_message(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__photon_chat_get_channel_sender(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_debug(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_connected(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_state_change(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_connection_error(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_client_error(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_warning(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_server_error(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_disconnected(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_status_update(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_get_messages(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_private_message(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_set_callback_receive_broadcast(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_get_broadcast_queue_count();
    public static native double __EXT_JNI__photon_chat_clear_broadcast_queue();
    public static native double __EXT_JNI__photon_chat_peek_next_broadcast_size();
    public static native String __EXT_JNI__photon_chat_peek_next_broadcast_channel();
    public static native double __EXT_JNI__photon_chat_receive_one_broadcast_buffer(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_chat_remove_callback_debug();
    public static native double __EXT_JNI__photon_chat_remove_callback_connected();
    public static native double __EXT_JNI__photon_chat_remove_callback_state_change();
    public static native double __EXT_JNI__photon_chat_remove_callback_connection_error();
    public static native double __EXT_JNI__photon_chat_remove_callback_client_error();
    public static native double __EXT_JNI__photon_chat_remove_callback_warning();
    public static native double __EXT_JNI__photon_chat_remove_callback_server_error();
    public static native double __EXT_JNI__photon_chat_remove_callback_disconnected();
    public static native double __EXT_JNI__photon_chat_remove_callback_status_update();
    public static native double __EXT_JNI__photon_chat_remove_callback_get_messages();
    public static native double __EXT_JNI__photon_chat_remove_callback_private_message();
    public static native double __EXT_JNI__photon_chat_remove_callback_receive_broadcast();
    public static native double __EXT_JNI__photon_voice_init();
    public static native double __EXT_JNI__photon_voice_shutdown();
    public static native double __EXT_JNI__photon_voice_service();
    public static native double __EXT_JNI__photon_voice_is_initialized();
    public static native double __EXT_JNI__photon_voice_notify_joined_room();
    public static native double __EXT_JNI__photon_voice_on_join_channel(double channel_id);
    public static native double __EXT_JNI__photon_voice_on_leave_channel(double channel_id);
    public static native double __EXT_JNI__photon_voice_on_join_all_channels();
    public static native double __EXT_JNI__photon_voice_on_leave_all_channels();
    public static native double __EXT_JNI__photon_voice_on_player_join(double channel_id, double player_id);
    public static native double __EXT_JNI__photon_voice_on_player_leave(double channel_id, double player_id);
    public static native double __EXT_JNI__photon_voice_create_local_voice(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_voice_remove_local_voice(double voice_id);
    public static native double __EXT_JNI__photon_voice_push_frame_buffer(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_voice_get_frame_queue_count();
    public static native double __EXT_JNI__photon_voice_clear_frame_queue();
    public static native double __EXT_JNI__photon_voice_peek_next_frame_size();
    public static native double __EXT_JNI__photon_voice_peek_next_frame_player_id();
    public static native double __EXT_JNI__photon_voice_peek_next_frame_voice_id();
    public static native double __EXT_JNI__photon_voice_receive_frame_buffer(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_voice_get_remote_voice_count();
    public static native double __EXT_JNI__photon_voice_get_remote_voice_player_id(double index);
    public static native double __EXT_JNI__photon_voice_get_remote_voice_id(double index);
    public static native double __EXT_JNI__photon_voice_get_remote_voice_codec(double index, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_voice_get_remote_voice_sample_rate(double index);
    public static native double __EXT_JNI__photon_voice_get_remote_voice_channels(double index);
    public static native double __EXT_JNI__photon_voice_get_remote_voice_is_speaking(double index);
    public static native double __EXT_JNI__photon_voice_get_frames_sent();
    public static native double __EXT_JNI__photon_voice_get_frames_received();
    public static native double __EXT_JNI__photon_voice_get_frames_lost();
    public static native double __EXT_JNI__photon_voice_get_round_trip_time();
    public static native double __EXT_JNI__photon_voice_get_round_trip_time_variance();
    public static native double __EXT_JNI__photon_voice_set_callback_remote_voice_added(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_voice_set_callback_remote_voice_removed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_voice_set_callback_speaking_changed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_voice_set_callback_debug(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_voice_remove_callback_remote_voice_added();
    public static native double __EXT_JNI__photon_voice_remove_callback_remote_voice_removed();
    public static native double __EXT_JNI__photon_voice_remove_callback_speaking_changed();
    public static native double __EXT_JNI__photon_voice_remove_callback_debug();
    public static native double __EXT_JNI__photon_voice_local_voice_set_transmit(double voice_id, double enabled);
    public static native double __EXT_JNI__photon_voice_local_voice_get_transmit(double voice_id);
    public static native double __EXT_JNI__photon_voice_set_remote_player_muted(double player_id, double muted);
    public static native double __EXT_JNI__photon_voice_get_remote_player_muted(double player_id);
    public static native double __EXT_JNI__photon_voice_set_remote_player_volume(double player_id, double volume);
    public static native double __EXT_JNI__photon_voice_get_remote_player_volume(double player_id);
    public static native double __EXT_JNI__photon_voice_get_debug_lost_percent();
    public static native double __EXT_JNI__photon_voice_set_debug_lost_percent(double percent);
    public static native double __EXT_JNI__photon_voice_get_speaking_threshold_ms();
    public static native double __EXT_JNI__photon_voice_set_speaking_threshold_ms(double ms);
    public static native double __EXT_JNI__photon_realtime_peer_get_state();
    public static native double __EXT_JNI__photon_realtime_peer_get_round_trip_time();
    public static native double __EXT_JNI__photon_realtime_peer_get_round_trip_time_variance();
    public static native double __EXT_JNI__photon_realtime_peer_get_bytes_in();
    public static native double __EXT_JNI__photon_realtime_peer_get_bytes_out();
    public static native double __EXT_JNI__photon_realtime_peer_get_queued_incoming_commands();
    public static native double __EXT_JNI__photon_realtime_peer_get_queued_outgoing_commands();
    public static native double __EXT_JNI__photon_realtime_peer_get_debug_output_level(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_realtime_peer_set_debug_output_level(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_realtime_peer_get_disconnect_timeout();
    public static native double __EXT_JNI__photon_realtime_peer_set_disconnect_timeout(double timeout_ms);
    public static native double __EXT_JNI__photon_realtime_peer_get_time_ping_interval();
    public static native double __EXT_JNI__photon_realtime_peer_set_time_ping_interval(double interval_ms);
    public static native double __EXT_JNI__photon_realtime_peer_get_crc_enabled();
    public static native double __EXT_JNI__photon_realtime_peer_set_crc_enabled(double enabled);
    public static native double __EXT_JNI__photon_realtime_peer_get_packet_loss_by_crc();
    public static native double __EXT_JNI__photon_realtime_peer_get_timestamp_of_last_socket_receive();
    public static native double __EXT_JNI__photon_realtime_peer_reset_traffic_stats();
    public static native double __EXT_JNI__photon_chat_peer_get_state();
    public static native double __EXT_JNI__photon_chat_peer_get_round_trip_time();
    public static native double __EXT_JNI__photon_chat_peer_get_round_trip_time_variance();
    public static native double __EXT_JNI__photon_chat_peer_get_bytes_in();
    public static native double __EXT_JNI__photon_chat_peer_get_bytes_out();
    public static native double __EXT_JNI__photon_chat_peer_get_queued_incoming_commands();
    public static native double __EXT_JNI__photon_chat_peer_get_queued_outgoing_commands();
    public static native double __EXT_JNI__photon_chat_peer_get_debug_output_level(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_chat_peer_set_debug_output_level(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_chat_peer_get_disconnect_timeout();
    public static native double __EXT_JNI__photon_chat_peer_set_disconnect_timeout(double timeout_ms);
    public static native double __EXT_JNI__photon_chat_peer_get_time_ping_interval();
    public static native double __EXT_JNI__photon_chat_peer_set_time_ping_interval(double interval_ms);
    public static native double __EXT_JNI__photon_chat_peer_get_crc_enabled();
    public static native double __EXT_JNI__photon_chat_peer_set_crc_enabled(double enabled);
    public static native double __EXT_JNI__photon_chat_peer_get_packet_loss_by_crc();
    public static native double __EXT_JNI__photon_chat_peer_get_timestamp_of_last_socket_receive();
    public static native double __EXT_JNI__photon_chat_peer_reset_traffic_stats();
    public static native double __EXT_JNI__photon_peer_network_sim_get_enabled();
    public static native double __EXT_JNI__photon_peer_network_sim_set_enabled(double enabled);
    public static native double __EXT_JNI__photon_peer_network_sim_set_lag(double incoming_ms, double outgoing_ms);
    public static native double __EXT_JNI__photon_peer_network_sim_set_jitter(double incoming_ms, double outgoing_ms);
    public static native double __EXT_JNI__photon_peer_network_sim_set_packet_loss(double incoming_pct, double outgoing_pct);
    public static native double __EXT_JNI__photon_common_set_debug_level(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__photon_common_get_debug_level(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__photon_common_get_serialization_protocol(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native String __EXT_JNI__photon_common_type_code_to_string(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__photon_common_get_sdk_version();
    public static native String __EXT_JNI__photon_common_client_state_to_string(double state);
    public static native String __EXT_JNI__photon_common_disconnect_cause_to_string(double cause);
}